### ISSUE TITLE
I am using GNU tools ARM Embedded v7.3.1 with IDE keil uv5.24

### ISSUE THREAD

**Issue by Isawwad** [particle-iot/device-os#1560] opened 2018-07-15 09:36 UTC
...in order to compile your code and it compiles just fine but when it comes to the C++ part the linker fails and give me bad final value,// c:/program files (x86)/gnu tools arm embedded/7 2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m\libc.a(lib_a-signalr.o): In function `_kill_r':, :: c:/program files (x86)/gnu tools arm embedded/7 2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m\libc.a(lib_a-abort.o): In function `abort':,abort.c:(.text.abort+0xa): undefined reference to `_exit', signalr.c:(.text._kill_r+0x10): undefined reference to `_kill'////// Why it uses libc.a to link a C++ file !!!

**Comment by rickkas7** [comment] 2018-07-15 09:48
At this time, the only supported gcc-arm compiler is version 5.3.1 (5-2016-q1-update).

It appears that you are using 7.3.1. It's unlikely that you will be able to get that to work properly.

**Comment by Isawwad** [comment] 2018-07-15 12:16
i tried even to include one cpp file to the c-files  written in it test code when i try to call the constructor of the class i get this messages 
c:/program files (x86)/gnu tools arm embedded/7 2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m\libc.a(lib_a-abort.o): In function `abort':
abort.c:(.text.abort+0xa): undefined reference to `_exit'
c:/program files (x86)/gnu tools arm embedded/7 2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m\libc.a(lib_a-sbrkr.o): In function `_sbrk_r':
sbrkr.c:(.text._sbrk_r+0xc): undefined reference to `_sbrk'
c:/program files (x86)/gnu tools arm embedded/7 2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m\libc.a(lib_a-signalr.o): In function `_kill_r':
signalr.c:(.text._kill_r+0x10): undefined reference to `_kill'
c:/program files (x86)/gnu tools arm embedded/7 2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m\libc.a(lib_a-signalr.o): In function `_getpid_r':
signalr.c:(.text._getpid_r+0x0): undefined reference to `_getpid'
collect2.exe: error: ld returned 1 exit status

**Comment by ScruffR** [comment] 2018-09-23 17:30
This issue should be closed as it's just a duplicate of #1565, but less info.

**Closed** 2020-03-03 11:20 UTC
